### ISSUE TITLE
Unable to compile `develop`

### ISSUE THREAD

**Issue by dignifiedquire** [textileio/ipc#1]
Running `make` results in 

```
error[E0433]: failed to resolve: use of undeclared crate or module `multihash`
  --> /Users/dignifiedquire/.cargo/registry/src/index.crates.io-6f17d22bba15001f/multihash-0.18.1/src/multihash_impl.rs:11:34
   |
11 | #[derive(Copy, Clone, Debug, Eq, Multihash, PartialEq)]
   |                                  ^^^^^^^^^ use of undeclared crate or module `multihash`
   |
   = note: this error originates in the derive macro `Multihash` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by vmx** [comment]
You could try to add the `multihash-impl` feature to [`multihash` in the Cargo.toml](https://github.com/textileio/ipc/blob/9152820acf085df9752840363c70348a5bd62111/Cargo.toml#L126).

**Comment by dignifiedquire** [comment]
additional note: it seems to only fail on macos, and not on linux 🤷

**Comment by dignifiedquire** [comment]
after nuking my clone (which was already fresh) and redoing the setup it now works..no idea what the problem was

**Comment by sanderpick** [comment]
hmm, I've never seen this on a fresh clone but haven't tried on mac... @avichalp does this ring a bell?

**Comment by avichalp** [comment]
Not sure what happened there. I just did a fresh clone on MacOS 14.2.1 and it worked fine.
